source s_network {
    network(ip("0.0.0.0") port(514) transport("udp") flags(store-raw-message));
    network(ip("0.0.0.0") port(514) transport("tcp") max-connections(200) flags(store-raw-message));
};
