rewrite r_common {
    set("${ISODATE}" value("@timestamp"));
    set("${R_ISODATE}" value("received_at"));
    set("${RAWMSG}" value("raw_message"));
    set("${MESSAGE}" value("message"));
    set("${SOURCEIP}" value("source.ip"));
    set("${FACILITY}" value("syslog.facility"));
    set("${LEVEL}" value("syslog.severity"));
    set("${LEVEL_NUM}" value("event.severity"));
    set("${PROGRAM}" value("syslog.program"));
    set("${HOST}" value("host.name"));
};
